Copy solidus_auth_devise UserMailer with views
Fixes

```
  1) Checkout without payment being required associate an incomplete guest order with user after successful password reset
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: token = token_url_regex.match(reset_password_email.body.to_s)[1]

          NoMethodError:
            undefined method `body' for nil:NilClass
          # ./spec/features/checkout_spec.rb:115:in `block (3 levels) in <top (required)>'

     1.2) Failure/Error: self.resource = resource_class.send_reset_password_instructions(params[resource_name])

          ActionView::MissingTemplate:
            Missing template spree/user_mailer/reset_password_instructions with "mailer". Searched in:
              * "spree/user_mailer"
          # ./app/controllers/spree/user_passwords_controller.rb:19:in `create'
          # ------------------
          # --- Caused by: ---
          # Capybara::CapybaraError:
          #   Your application server raised an error - It has been raised in your test code because Capybara.raise_server_errors == true
          #   /home/gsmendoza/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/capybara-3.35.3/lib/capybara/session.rb:160:in `raise_server_error!'
```